name: "Update dataset"
on:
    schedule:
        - cron: "0 8 * * *"
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install PNPM
              run: npm install -g pnpm

            - name: Sync node version and setup cache
              uses: actions/setup-node@v3
              with:
                  node-version: "lts/*"
                  cache: "pnpm"

            - name: Install app dependencies
              run: pnpm install

            - name: Update S3 dataset
              run: pnpm update:data
              env:
                  S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
                  S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
                  S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
