name: "Update dataset"
on:
    schedule:
        - cron: "0 12 * * *"
    workflow_dispatch:

defaults:
    run:
        working-directory: apps/dataset

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install PNPM
              run: npm install -g pnpm

            - name: Sync node version and setup cache
              uses: actions/setup-node@v4
              with:
                  node-version: "lts/*"
                  cache: "pnpm"

            - name: Install app dependencies
              run: pnpm install

            # - name: Install Playwright Browsers
            #   run: npx playwright install --with-deps

            - name: Update S3 dataset
              run: pnpm start
              env:
                  S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
                  S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
                  S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
