name: Release
on:
    push:
        tags:
            - "v*"
    workflow_dispatch:

jobs:
    release:
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-latest, windows-latest] # ubuntu-20.04,
        runs-on: ${{ matrix.platform }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            # - name: Install dependencies (ubuntu only)
            # if: matrix.platform == 'ubuntu-20.04'
            # # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
            # run: |
            #     sudo apt-get update
            #     sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

            - name: Rust setup
              uses: dtolnay/rust-toolchain@stable

            - name: Rust cache
              uses: swatinem/rust-cache@v2
              with:
                  workspaces: "./src-tauri -> target"

            - name: Install PNPM
              run: npm install -g pnpm

            - name: Sync node version and setup cache
              uses: actions/setup-node@v3
              with:
                  node-version: "lts/*"
                  cache: "pnpm" # Set this to npm, yarn or pnpm.

            - name: Install app dependencies
              # Remove `&& yarn build` if you build your frontend in `beforeBuildCommand`
              run: pnpm install # Change this to npm, yarn or pnpm.

            - name: Build the app
              uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
                  VITE_GA_TAG: "G-967XTGK665"
              with:
                  tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
                  releaseName: "DraftGap v__VERSION__" # tauri-action replaces \_\_VERSION\_\_ with the app version.
                  releaseBody: "# Download DraftGap\n[Windows](https://github.com/vigovlugt/draftgap/releases/download/v__VERSION__/DraftGap___VERSION___x64_en-US.msi)\n[Mac](https://github.com/vigovlugt/draftgap/releases/download/v__VERSION__/DraftGap.app.tar.gz)"
                  releaseDraft: false
                  prerelease: false

    publish:
        runs-on: ubuntu-20.04
        needs: [release]
        permissions: write-all
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install PNPM
              run: npm install -g pnpm

            - name: Sync node version and setup cache
              uses: actions/setup-node@v3
              with:
                  node-version: "lts/*"
                  cache: "pnpm" # Set this to npm, yarn or pnpm.

            - name: Install app dependencies
              run: pnpm install

            - name: Update tauri-update gist
              run: pnpm publish:tauri-update
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
                  S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
                  S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
                  S3_ENDPOINT: https://6239efaaf63b138409f3ff6e44602435.r2.cloudflarestorage.com/draftgap
                  GIST_ID: "5d549f4fdd602eb22542ef55e7c881ec"
                  REPOSITORY_OWNER: vigovlugt
                  REPOSITORY_NAME: draftgap
